[package]
name = "dagger"
version = "0.1.0"
edition = "2021"

[lib]
name = "shared"

[dependencies]
clap = { version = "4.5.16", features = ["derive", "env"] }
dagger-sdk = "0.11.10"
eyre = "0.6.12"
tokio = "1.39.3"
tracing-subscriber = "0.3.18"
trait-variant = "0.1.2"
